permallink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://use.typekit.net/rld0uvc.css"
  colors:
    patterns:
      brand.logos: "--color-secondary"
      buttons.ghost: "--color-secondary"
      cards: "--color-secondary"
