title: "Cards"
description: |
  this is a card. used to display the products of on the website.

patterns:
  cards:
    title: "card"
    description: |
      This is the basic card.
    fields:
      - name: text
        type: string
        example: "Blue Kush"
